### ISSUE TITLE
Add a license to the repository.

### ISSUE THREAD

**Issue by domdfcoding** [salabim/easy_property#1]
Hello,

I am interested in using easy_property, but there is currently no license set for the repository. Would you be able to add a license?

If you're unsure which license to use, have a look at https://choosealicense.com/

There are also instructions on how to add the license if you are unfamiliar: https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

Thanks 😃

**Comment by salabim** [comment]
Done.
